import type { IndicatorCategory } from "@/lib/enums";

// Canonical indicator catalogue. `code` matches the World Bank API series id so
// the same definition drives both ingestion and the UI. Adding a new indicator
// is a one-line change here — no schema migration required.
export interface IndicatorDef {
  code: string;
  slug: string;
  name: string;
  shortName: string;
  description: string;
  unit: string;
  category: IndicatorCategory;
  higherIsBetter: boolean | null;
  decimals: number;
  source: string; // DataSource.code
}

export const INDICATORS: IndicatorDef[] = [
  {
    code: "SP.DYN.TFRT.IN",
    slug: "fertility-rate",
    name: "Total Fertility Rate",
    shortName: "Fertility Rate",
    description:
      "Average number of children that would be born to a woman over her lifetime given current age-specific fertility rates. Pre-1960 values are long-run historical reconstructions from Gapminder; from 1960 onward this is World Bank WDI.",
    unit: "births per woman",
    category: "FERTILITY",
    higherIsBetter: null,
    decimals: 2,
    source: "WORLD_BANK",
  },
  {
    code: "SP.DYN.CBRT.IN",
    slug: "birth-rate",
    name: "Crude Birth Rate",
    shortName: "Birth Rate",
    description:
      "Live births per 1,000 people per year. Not adjusted for age structure, so a country with many young adults shows a higher rate than an older one even at identical fertility.",
    unit: "per 1,000 people",
    category: "FERTILITY",
    higherIsBetter: null,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SP.DYN.CDRT.IN",
    slug: "death-rate",
    name: "Crude Death Rate",
    shortName: "Death Rate",
    description:
      "Deaths per 1,000 people per year. Not adjusted for age structure, so an ageing country can show a rising rate while mortality risk at every age is still falling.",
    unit: "per 1,000 people",
    category: "MORTALITY",
    higherIsBetter: false,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SP.POP.TOTL",
    slug: "population",
    name: "Total Population",
    shortName: "Population",
    description: "Total resident population, all ages and both sexes.",
    unit: "people",
    category: "POPULATION",
    higherIsBetter: null,
    decimals: 0,
    source: "WORLD_BANK",
  },
  {
    code: "SP.POP.GROW",
    slug: "population-growth",
    name: "Population Growth",
    shortName: "Pop. Growth",
    description:
      "Annual percentage change in total population, combining births, deaths, and net migration. A country can grow while births fall, if migration more than compensates.",
    unit: "% annual",
    category: "POPULATION",
    higherIsBetter: null,
    decimals: 2,
    source: "WORLD_BANK",
  },
  {
    code: "SP.DYN.LE00.IN",
    slug: "life-expectancy",
    name: "Life Expectancy at Birth",
    shortName: "Life Expectancy",
    description:
      "Number of years a newborn would live if mortality patterns at birth stayed constant. Pre-1960 values from Our World in Data long-run reconstructions (Riley, Zijdeman, HMD, UN); from 1960 World Bank WDI.",
    unit: "years",
    category: "MORTALITY",
    higherIsBetter: true,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SP.URB.TOTL.IN.ZS",
    slug: "urban-population",
    name: "Urban Population",
    shortName: "Urban %",
    description: "Share of the population living in urban areas (%).",
    unit: "% of total",
    category: "POPULATION",
    higherIsBetter: null,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SM.POP.NETM",
    slug: "net-migration",
    name: "Net Migration",
    shortName: "Net Migration",
    description:
      "Net number of migrants (immigrants minus emigrants) in a year.",
    unit: "people",
    category: "MIGRATION",
    higherIsBetter: null,
    decimals: 0,
    source: "WORLD_BANK",
  },
  {
    code: "SP.POP.0014.TO.ZS",
    slug: "pop-share-0-14",
    name: "Population Ages 0–14 (% of total)",
    shortName: "Ages 0–14",
    description:
      "Share of the population aged 0–14. Used to anchor the current age structure for projections.",
    unit: "% of population",
    category: "POPULATION",
    higherIsBetter: null,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SP.POP.1564.TO.ZS",
    slug: "pop-share-15-64",
    name: "Population Ages 15–64 (% of total)",
    shortName: "Ages 15–64",
    description:
      "Share of the population of working age (15–64). Used to anchor the current age structure for projections.",
    unit: "% of population",
    category: "POPULATION",
    higherIsBetter: null,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SP.POP.65UP.TO.ZS",
    slug: "pop-share-65-plus",
    name: "Population Ages 65+ (% of total)",
    shortName: "Ages 65+",
    description:
      "Share of the population aged 65 and over. Used to anchor the current age structure for projections.",
    unit: "% of population",
    category: "POPULATION",
    higherIsBetter: null,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SM.POP.TOTL",
    slug: "migrant-stock",
    name: "Foreign-born Population",
    shortName: "Foreign-born",
    description:
      "International migrant stock — the number of people living in a country who were born in another country (the immigrant / diaspora population).",
    unit: "people",
    category: "MIGRATION",
    higherIsBetter: null,
    decimals: 0,
    source: "WORLD_BANK",
  },
  {
    code: "SM.POP.TOTL.ZS",
    slug: "migrant-stock-share",
    name: "Foreign-born Population (% of total)",
    shortName: "Foreign-born %",
    description:
      "International migrant stock as a share of the total population — how large the foreign-born / diaspora population is relative to the country.",
    unit: "% of population",
    category: "MIGRATION",
    higherIsBetter: null,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "NY.GDP.MKTP.CD",
    slug: "gdp",
    name: "GDP (current US$)",
    shortName: "GDP",
    description:
      "Market value of all goods and services produced in a year, converted to US dollars at market exchange rates. Measured in current prices, so figures from different years are not directly comparable — part of any increase is inflation and currency movement rather than more output.",
    unit: "current US$",
    category: "ECONOMY",
    higherIsBetter: true,
    decimals: 0,
    source: "WORLD_BANK",
  },
  {
    code: "NY.GDP.PCAP.CD",
    slug: "gdp-per-capita",
    name: "GDP per Capita (current US$)",
    shortName: "GDP / capita",
    description:
      "GDP divided by midyear population, at market exchange rates. Not adjusted for local price levels, so it understates real living standards in countries where goods and services are cheap.",
    unit: "current US$",
    category: "ECONOMY",
    higherIsBetter: true,
    decimals: 0,
    source: "WORLD_BANK",
  },
  {
    code: "NY.GDP.MKTP.KD.ZG",
    slug: "gdp-growth",
    name: "GDP Growth",
    shortName: "GDP Growth",
    description:
      "Annual change in GDP measured at constant prices. Unlike the level figures, this series is adjusted for inflation, so it reflects real changes in output.",
    unit: "% annual",
    category: "ECONOMY",
    higherIsBetter: true,
    decimals: 2,
    source: "WORLD_BANK",
  },
  {
    code: "NY.GDP.MKTP.KD",
    slug: "gdp-real",
    name: "GDP (constant 2015 US$)",
    shortName: "Real GDP",
    description:
      "Total output valued at 2015 prices, so changes over time show real growth rather than inflation. Converted at 2015 exchange rates, which makes it the right series for tracking one country through time but a poorer one for comparing levels between countries.",
    unit: "constant 2015 US$",
    category: "ECONOMY",
    higherIsBetter: true,
    decimals: 0,
    source: "WORLD_BANK",
  },
  {
    code: "NY.GDP.PCAP.KD",
    slug: "gdp-per-capita-real",
    name: "GDP per Capita (constant 2015 US$)",
    shortName: "Real GDP / capita",
    description:
      "Output per person at constant 2015 prices. Use this rather than the current-dollar series to ask whether a country actually produces more per person than it did a decade ago, since inflation is removed.",
    unit: "constant 2015 US$",
    category: "ECONOMY",
    higherIsBetter: true,
    decimals: 0,
    source: "WORLD_BANK",
  },
  {
    code: "NY.GDP.PCAP.PP.CD",
    slug: "gdp-per-capita-ppp",
    name: "GDP per Capita, PPP (current international $)",
    shortName: "GDP / capita (PPP)",
    description:
      "Output per person converted at purchasing-power-parity rates instead of market exchange rates, so a dollar buys a comparable basket of goods in every country. The standard measure for comparing material living standards across countries.",
    unit: "current international $",
    category: "ECONOMY",
    higherIsBetter: true,
    decimals: 0,
    source: "WORLD_BANK",
  },
  {
    code: "NY.GDP.PCAP.PP.KD",
    slug: "gdp-per-capita-ppp-real",
    name: "GDP per Capita, PPP (constant 2021 international $)",
    shortName: "GDP / capita (PPP, real)",
    description:
      "Purchasing-power-parity output per person held at constant 2021 prices, adjusted for both local price levels and inflation. The most directly comparable living-standards series on this site, across countries and across years.",
    unit: "constant 2021 international $",
    category: "ECONOMY",
    higherIsBetter: true,
    decimals: 0,
    source: "WORLD_BANK",
  },
  {
    code: "NY.GNP.PCAP.CD",
    slug: "gni-per-capita",
    name: "GNI per Capita, Atlas Method (current US$)",
    shortName: "GNI / capita",
    description:
      "Income earned by a country's residents per person, smoothed over three years by the World Bank Atlas method. GNI counts income wherever residents earn it, so it diverges from GDP where foreign-owned profits or remittances are large. This is the series used to assign income groups.",
    unit: "current US$",
    category: "ECONOMY",
    higherIsBetter: true,
    decimals: 0,
    source: "WORLD_BANK",
  },
  {
    code: "FP.CPI.TOTL.ZG",
    slug: "inflation",
    name: "Inflation, Consumer Prices",
    shortName: "Inflation",
    description:
      "Annual change in the cost of a representative basket of consumer goods and services. Each country sets its own basket and method, so the direction and size of movements travel better across borders than the exact levels.",
    unit: "% annual",
    category: "ECONOMY",
    higherIsBetter: null,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SL.UEM.TOTL.ZS",
    slug: "unemployment",
    name: "Unemployment Rate",
    shortName: "Unemployment",
    description:
      "Share of the labour force without work but available for and seeking employment, harmonised to the ILO definition. People who have stopped looking are outside the labour force and are not counted, so the rate can fall as discouragement rises.",
    unit: "% of labour force",
    category: "ECONOMY",
    higherIsBetter: false,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SI.POV.GINI",
    slug: "gini",
    name: "Gini Index",
    shortName: "Gini (inequality)",
    description:
      "Income inequality on a 0–100 scale, where 0 is perfect equality and 100 is one household holding all income. Built from household surveys run in different years and to different designs, so coverage is patchy and cross-country gaps of a point or two are not meaningful.",
    unit: "index (0–100)",
    category: "ECONOMY",
    higherIsBetter: false,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SL.TLF.CACT.FE.ZS",
    slug: "female-labour-force",
    name: "Female Labour Force Participation",
    shortName: "Female LFP",
    description:
      "Share of women aged 15 and over who are working or looking for work, modelled ILO estimate. Historically inversely related to fertility, though across rich countries the correlation has reversed since the 1980s — the highest-participation countries now tend to have the higher birth rates.",
    unit: "% of women 15+",
    category: "ECONOMY",
    higherIsBetter: null,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "NE.EXP.GNFS.ZS",
    slug: "exports-share-gdp",
    name: "Exports of Goods and Services (% of GDP)",
    shortName: "Exports / GDP",
    description:
      "Exported goods and services as a share of GDP — roughly, how exposed an economy is to world demand. Can exceed 100% in entrepôt economies where imports are processed and re-exported.",
    unit: "% of GDP",
    category: "ECONOMY",
    higherIsBetter: null,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SP.DYN.IMRT.IN",
    slug: "infant-mortality",
    name: "Infant Mortality Rate",
    shortName: "Infant mortality",
    description:
      "Deaths before the first birthday per 1,000 live births. Sensitive to registration practice at the edge of viability: countries that record extremely premature births as live births rather than stillbirths report higher rates for the same underlying medical outcomes.",
    unit: "per 1,000 live births",
    category: "MORTALITY",
    higherIsBetter: false,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SH.STA.MMRT",
    slug: "maternal-mortality",
    name: "Maternal Mortality Ratio",
    shortName: "Maternal mortality",
    description:
      "Deaths from causes related to pregnancy or childbirth per 100,000 live births, within 42 days of the end of pregnancy. A modelled estimate — few countries measure this directly with complete civil registration.",
    unit: "per 100,000 live births",
    category: "MORTALITY",
    higherIsBetter: false,
    decimals: 0,
    source: "WORLD_BANK",
  },
  {
    code: "SP.DYN.LE00.FE.IN",
    slug: "life-expectancy-female",
    name: "Life Expectancy at Birth, Female",
    shortName: "Life expectancy (F)",
    description:
      "Years a newborn girl would live under current mortality patterns. Women outlive men almost everywhere; the size of the gap, not its direction, is what varies.",
    unit: "years",
    category: "MORTALITY",
    higherIsBetter: true,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SP.DYN.LE00.MA.IN",
    slug: "life-expectancy-male",
    name: "Life Expectancy at Birth, Male",
    shortName: "Life expectancy (M)",
    description:
      "Years a newborn boy would live under current mortality patterns. Read against the female series: the gap runs from about two years to over ten, widening where male deaths from injury, alcohol and smoking are common.",
    unit: "years",
    category: "MORTALITY",
    higherIsBetter: true,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SH.STA.SUIC.P5",
    slug: "suicide-rate",
    name: "Suicide Mortality Rate",
    shortName: "Suicide rate",
    description:
      "Suicide deaths per 100,000 people, age-standardised WHO estimate. Classification depends on legal and religious context as well as medicine, and undercounting is thought to be substantial in some countries.",
    unit: "per 100,000",
    category: "MORTALITY",
    higherIsBetter: false,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SP.ADO.TFRT",
    slug: "adolescent-fertility",
    name: "Adolescent Fertility Rate",
    shortName: "Teen fertility",
    description:
      "Births per 1,000 women aged 15–19. Typically falls earlier and faster than overall fertility as schooling and contraception spread, which makes it a useful marker of how far a country is through the fertility transition.",
    unit: "per 1,000 women 15–19",
    category: "FERTILITY",
    higherIsBetter: null,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SP.DYN.CONU.ZS",
    slug: "contraceptive-prevalence",
    name: "Contraceptive Prevalence, Any Method",
    shortName: "Contraceptive use",
    description:
      "Share of married or in-union women aged 15–49 using any method of contraception. Survey-based, so values exist only for the years a country ran a demographic or health survey and gaps of a decade are common.",
    unit: "% of women 15–49",
    category: "FERTILITY",
    higherIsBetter: null,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "EN.POP.DNST",
    slug: "population-density",
    name: "Population Density",
    shortName: "Density",
    description:
      "People per square kilometre of land area. Land area includes desert, mountain and ice, so national density says little about how crowded the inhabited parts of a country actually are.",
    unit: "people per sq km",
    category: "POPULATION",
    higherIsBetter: null,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SP.RUR.TOTL.ZS",
    slug: "rural-population",
    name: "Rural Population (% of total)",
    shortName: "Rural %",
    description:
      "Share of people living outside areas classified as urban — the complement of the urban share. Each country sets its own urban definition, so this reads best within a country over time rather than across borders.",
    unit: "% of total",
    category: "POPULATION",
    higherIsBetter: null,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SP.POP.TOTL.FE.ZS",
    slug: "female-population-share",
    name: "Female Share of Population",
    shortName: "Female %",
    description:
      "Women as a share of the total population. Departures from roughly 50% reflect sex selection at birth, the gap between male and female mortality, and heavily sex-imbalanced labour migration.",
    unit: "% of population",
    category: "POPULATION",
    higherIsBetter: null,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SP.URB.GROW",
    slug: "urban-population-growth",
    name: "Urban Population Growth",
    shortName: "Urban growth",
    description:
      "Annual change in the population living in urban areas. Combines natural increase in cities, migration from the countryside, and places being reclassified as urban — the third can move the series without anyone moving house.",
    unit: "% annual",
    category: "POPULATION",
    higherIsBetter: null,
    decimals: 2,
    source: "WORLD_BANK",
  },
  {
    code: "SP.POP.DPND",
    slug: "age-dependency-ratio",
    name: "Age Dependency Ratio",
    shortName: "Dependency ratio",
    description:
      "People under 15 and over 64 per 100 people of working age. A high ratio can mean many children or many pensioners — opposite fiscal situations — so read it alongside the age-structure shares.",
    unit: "% of working-age population",
    category: "POPULATION",
    higherIsBetter: null,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SH.XPD.CHEX.GD.ZS",
    slug: "health-expenditure",
    name: "Health Expenditure (% of GDP)",
    shortName: "Health spending",
    description:
      "All current spending on health, public and private, as a share of GDP. A ratio rather than a level: it can be high because care is expensive or because GDP is small.",
    unit: "% of GDP",
    category: "HEALTH",
    higherIsBetter: null,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SH.MED.BEDS.ZS",
    slug: "hospital-beds",
    name: "Hospital Beds",
    shortName: "Hospital beds",
    description:
      "Inpatient beds per 1,000 people across public, private and specialised facilities. Bed counts have fallen in most rich countries because stays are shorter and more surgery is same-day, not because capacity collapsed.",
    unit: "per 1,000 people",
    category: "HEALTH",
    higherIsBetter: null,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SE.ADT.LITR.ZS",
    slug: "literacy-rate",
    name: "Adult Literacy Rate",
    shortName: "Literacy",
    description:
      "Share of people aged 15 and over able to read and write a short simple statement about their everyday life. Usually collected by self-report in censuses and surveys, which tends to overstate ability.",
    unit: "% of adults",
    category: "EDUCATION",
    higherIsBetter: true,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SE.XPD.TOTL.GD.ZS",
    slug: "education-expenditure",
    name: "Government Expenditure on Education (% of GDP)",
    shortName: "Education spending",
    description:
      "Public spending on education at all levels as a share of GDP. Excludes private tuition and household spending, which is a large share of the total in parts of East Asia and Latin America.",
    unit: "% of GDP",
    category: "EDUCATION",
    higherIsBetter: null,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SE.SEC.ENRR",
    slug: "secondary-enrollment",
    name: "School Enrollment, Secondary (% gross)",
    shortName: "Secondary enrolment",
    description:
      "Secondary enrolment as a share of the population of official secondary-school age. Gross ratios count over-age and under-age pupils, so a value above 100% means repetition or late entry, not universal attendance.",
    unit: "% gross",
    category: "EDUCATION",
    higherIsBetter: null,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "SE.TER.ENRR",
    slug: "tertiary-enrollment",
    name: "School Enrollment, Tertiary (% gross)",
    shortName: "Tertiary enrolment",
    description:
      "Higher-education enrolment as a share of the population in the five years following secondary school. Rising tertiary enrolment among women is one of the strongest correlates of later and lower childbearing.",
    unit: "% gross",
    category: "EDUCATION",
    higherIsBetter: null,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "IT.NET.USER.ZS",
    slug: "internet-users",
    name: "Individuals Using the Internet",
    shortName: "Internet use",
    description:
      "Share of the population that used the internet in the previous three months. Some countries report from household surveys and others from operator data, which counts subscriptions rather than people.",
    unit: "% of population",
    category: "SOCIETY",
    higherIsBetter: null,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "EG.ELC.ACCS.ZS",
    slug: "electricity-access",
    name: "Access to Electricity",
    shortName: "Electricity access",
    description:
      "Share of the population with access to electricity, counting both grid connections and off-grid supply. Having a connection is not the same as having reliable power.",
    unit: "% of population",
    category: "SOCIETY",
    higherIsBetter: true,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    // Not a World Bank series — curated from WHO/Guttmacher. The code is a
    // stable internal id (kept out of the World Bank ingestion loop).
    code: "ABORTION.RATE",
    slug: "abortion-rate",
    name: "Abortion Rate",
    shortName: "Abortion Rate",
    description:
      "Induced abortions per 1,000 women aged 15–49 per year. Compiled from WHO and Guttmacher Institute estimates; reporting completeness varies by country.",
    unit: "per 1,000 women 15–49",
    category: "FERTILITY",
    higherIsBetter: null,
    decimals: 1,
    source: "WHO_GUTTMACHER",
  },
  {
    code: "VC.IHR.PSRC.P5",
    slug: "homicide-rate",
    name: "Intentional Homicide Rate",
    shortName: "Homicide Rate",
    description: "Intentional homicides per 100,000 people.",
    unit: "per 100,000",
    category: "CRIME",
    higherIsBetter: false,
    decimals: 1,
    source: "WORLD_BANK",
  },
  {
    code: "DIVORCE.RATE",
    slug: "divorce-rate",
    name: "Crude Divorce Rate",
    shortName: "Divorce Rate",
    description:
      "Divorces per 1,000 population per year. Compiled from OECD, Eurostat and UN statistics.",
    unit: "per 1,000 people",
    category: "SOCIETY",
    higherIsBetter: null,
    decimals: 1,
    source: "OECD",
  },
  {
    code: "BIRTHS.NONMARITAL",
    slug: "nonmarital-births",
    name: "Births Outside Marriage",
    shortName: "Nonmarital Births",
    description:
      "Share of live births to unmarried mothers (%). Compiled from OECD and Eurostat.",
    unit: "% of births",
    category: "SOCIETY",
    higherIsBetter: null,
    decimals: 1,
    source: "OECD",
  },
  {
    code: "HOME.OWNERSHIP",
    slug: "homeownership-rate",
    name: "Home Ownership Rate",
    shortName: "Home Ownership",
    description:
      "Share of households that own their home (%). Compiled from OECD, Eurostat and national statistics.",
    unit: "% of households",
    category: "HOUSING",
    higherIsBetter: null,
    decimals: 1,
    source: "OECD",
  },
  {
    // City-level urban agglomeration population, annual 1950–2035, from the UN
    // World Urbanization Prospects. Stored against City rows (subjectType=CITY).
    code: "CITY.POP.WUP",
    slug: "city-population",
    name: "Urban Agglomeration Population",
    shortName: "City Population",
    description:
      "Population of the urban agglomeration (contiguous built-up area), annual 1950–2035. Estimates through 2018 and UN projections thereafter.",
    unit: "people",
    category: "POPULATION",
    higherIsBetter: null,
    decimals: 0,
    source: "UN_WUP",
  },
  {
    // City / metro-area TFR from national statistical offices. Caller must run
    // ensureIndicators so slug "city-fertility" exists before seedCityFertility.
    code: "CITY.TFR",
    slug: "city-fertility",
    name: "City Total Fertility Rate",
    shortName: "City TFR",
    description:
      "Total fertility rate for a city or matching administrative geography (prefecture, borough set, département, etc.), compiled from national statistical offices. Geography notes on each series clarify the exact unit.",
    unit: "births per woman",
    category: "FERTILITY",
    higherIsBetter: null,
    decimals: 2,
    source: "NATIONAL_STATS",
  },
  {
    code: "CITY.FOREIGN.BORN.SHARE",
    slug: "city-foreign-born-share",
    name: "City Foreign-born / Foreign Citizenship Share",
    shortName: "City Foreign-born %",
    description:
      "Share of the city population that is foreign-born or holds foreign citizenship, per the definition used by the national statistical office (noted per series).",
    unit: "% of population",
    category: "MIGRATION",
    higherIsBetter: null,
    decimals: 1,
    source: "NATIONAL_STATS",
  },
  {
    // Age-structure shares stored with dimension="age" /
    // dimensionValue in {"0-14","15-64","65+"}.
    code: "CITY.AGE.SHARE",
    slug: "city-age-share",
    name: "City Population Age Share",
    shortName: "City Age Share",
    description:
      "Share of the city population in broad age groups (0–14, 15–64, 65+), from national censuses and official estimates. Breakdown via dimension=age.",
    unit: "% of population",
    category: "POPULATION",
    higherIsBetter: null,
    decimals: 1,
    source: "NATIONAL_STATS",
  },
  {
    code: "CITY.MEDIAN.INCOME",
    slug: "city-median-income",
    name: "City Median Household Income",
    shortName: "City median income",
    description:
      "Median household income for the city (Census place), U.S. dollars. U.S. cities from ACS.",
    unit: "current US$",
    category: "ECONOMY",
    higherIsBetter: true,
    decimals: 0,
    source: "US_CENSUS",
  },
  {
    code: "SP.DYN.TFRT.PROV",
    slug: "fertility-provisional",
    name: "Provisional Total Fertility Rate",
    shortName: "TFR (provisional)",
    description:
      "Provisional / nowcast total fertility rate compiled from national statistical offices (via BirthGauge). Covers recent years ahead of World Bank final series. Partial-year estimates may be revised.",
    unit: "births per woman",
    category: "FERTILITY",
    higherIsBetter: null,
    decimals: 2,
    source: "BIRTHGAUGE",
  },
  {
    code: "OECD.UNE.NB",
    slug: "unemployment-native-born",
    name: "Native-born Unemployment Rate",
    shortName: "Native-born unemployment",
    description:
      "Unemployment rate of native-born persons aged 15–64, as a share of the native-born labour force. OECD labour-market outcomes of immigrants.",
    unit: "% of labour force",
    category: "MIGRATION",
    higherIsBetter: false,
    decimals: 1,
    source: "OECD",
  },
  {
    code: "OECD.UNE.FB",
    slug: "unemployment-foreign-born",
    name: "Foreign-born Unemployment Rate",
    shortName: "Foreign-born unemployment",
    description:
      "Unemployment rate of foreign-born persons aged 15–64, as a share of the foreign-born labour force. OECD labour-market outcomes of immigrants.",
    unit: "% of labour force",
    category: "MIGRATION",
    higherIsBetter: false,
    decimals: 1,
    source: "OECD",
  },
  {
    code: "EUROSTAT.CRIM.PRIS.FOR",
    slug: "foreign-prisoner-share",
    name: "Foreign Citizenship Share of Prisoners",
    shortName: "Foreign prisoners",
    description:
      "Share of persons held in prison who hold foreign citizenship (%). Eurostat crim_pris_ctz. Citizenship is not the same as immigrant ancestry or migration background.",
    unit: "% of prisoners",
    category: "CRIME",
    higherIsBetter: null,
    decimals: 1,
    source: "EUROSTAT",
  },
  {
    code: "ADMIN1.GFR",
    slug: "general-fertility-rate",
    name: "General Fertility Rate",
    shortName: "GFR",
    description:
      "Live births per 1,000 women ages 15–44. Common U.S. NCHS state fertility measure (distinct from total fertility rate).",
    unit: "per 1,000 women 15–44",
    category: "FERTILITY",
    higherIsBetter: null,
    decimals: 1,
    source: "NATIONAL_STATS",
  },
  {
    code: "HMD.CDRT",
    slug: "historic-death-rate",
    name: "Historic Crude Death Rate",
    shortName: "Historic death rate",
    description:
      "Deaths per 1,000 people per year from the Human Mortality Database (via Our World in Data). Covers countries with long vital-registration series, in some cases back to the mid-18th century. Not age-standardized.",
    unit: "per 1,000 people",
    category: "MORTALITY",
    higherIsBetter: false,
    decimals: 1,
    source: "HMD",
  },
  {
    code: "OWID.U5MR",
    slug: "child-mortality",
    name: "Under-five Mortality Rate",
    shortName: "Child mortality",
    description:
      "Deaths of children under age 5 per 1,000 live births. Long-run series from Our World in Data (Gapminder historical estimates and UN IGME).",
    unit: "per 1,000 live births",
    category: "MORTALITY",
    higherIsBetter: false,
    decimals: 1,
    source: "OWID",
  },
];

export const INDICATOR_BY_SLUG = new Map(INDICATORS.map((i) => [i.slug, i]));
export const INDICATOR_BY_CODE = new Map(INDICATORS.map((i) => [i.code, i]));

// Convenience slugs referenced throughout the app.
export const SLUG = {
  fertility: "fertility-rate",
  birthRate: "birth-rate",
  deathRate: "death-rate",
  population: "population",
  populationGrowth: "population-growth",
  urbanPopulation: "urban-population",
  lifeExpectancy: "life-expectancy",
  netMigration: "net-migration",
  popShare0to14: "pop-share-0-14",
  popShare15to64: "pop-share-15-64",
  popShare65plus: "pop-share-65-plus",
  migrantStock: "migrant-stock",
  migrantStockShare: "migrant-stock-share",
  gdp: "gdp",
  gdpPerCapita: "gdp-per-capita",
  gdpGrowth: "gdp-growth",
  gdpReal: "gdp-real",
  gdpPerCapitaReal: "gdp-per-capita-real",
  gdpPerCapitaPpp: "gdp-per-capita-ppp",
  gdpPerCapitaPppReal: "gdp-per-capita-ppp-real",
  gniPerCapita: "gni-per-capita",
  inflation: "inflation",
  unemployment: "unemployment",
  gini: "gini",
  femaleLabourForce: "female-labour-force",
  exportsShareGdp: "exports-share-gdp",
  infantMortality: "infant-mortality",
  maternalMortality: "maternal-mortality",
  lifeExpectancyFemale: "life-expectancy-female",
  lifeExpectancyMale: "life-expectancy-male",
  suicideRate: "suicide-rate",
  adolescentFertility: "adolescent-fertility",
  contraceptivePrevalence: "contraceptive-prevalence",
  populationDensity: "population-density",
  ruralPopulation: "rural-population",
  femalePopulationShare: "female-population-share",
  urbanPopulationGrowth: "urban-population-growth",
  ageDependencyRatio: "age-dependency-ratio",
  healthExpenditure: "health-expenditure",
  hospitalBeds: "hospital-beds",
  literacyRate: "literacy-rate",
  educationExpenditure: "education-expenditure",
  secondaryEnrollment: "secondary-enrollment",
  tertiaryEnrollment: "tertiary-enrollment",
  internetUsers: "internet-users",
  electricityAccess: "electricity-access",
  abortionRate: "abortion-rate",
  homicideRate: "homicide-rate",
  divorceRate: "divorce-rate",
  nonmaritalBirths: "nonmarital-births",
  homeownershipRate: "homeownership-rate",
  cityPopulation: "city-population",
  cityFertility: "city-fertility",
  cityForeignBornShare: "city-foreign-born-share",
  cityAgeShare: "city-age-share",
  cityMedianIncome: "city-median-income",
  fertilityProvisional: "fertility-provisional",
  unemploymentNativeBorn: "unemployment-native-born",
  unemploymentForeignBorn: "unemployment-foreign-born",
  foreignPrisonerShare: "foreign-prisoner-share",
  generalFertilityRate: "general-fertility-rate",
  historicDeathRate: "historic-death-rate",
  childMortality: "child-mortality",
} as const;
